name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.5.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.5.0
    - run: npm install -g npm@6.14.11
    - run: npm test
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/ang-website
        BUILD_SCRIPT: npm install && npm run build -- --prod